application: foodcider-156622
runtime: python27
api_version: 1
version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: FoodProject_controller.app
  

# [END handlers]

# [START libraries]
libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
# [END libraries]
